name: ascend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.0.2
  intl: ^0.20.0
  camera: ^0.10.5+3
  google_mlkit_commons: ^0.7.1
  google_mlkit_pose_detection: ^0.12.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  google_sign_in: ^6.2.2
  flutter_tts: ^4.2.2
  image: ^4.5.2
  flame: ^1.8.0
  flame_forge2d: ^0.13.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Ascend.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/game_images/
    - assets/images/game_images/male/
    - assets/images/game_images/female/
    - assets/images/game_images/male/Archer/
    - assets/images/game_images/male/Swordsman/
    - assets/images/game_images/male/Wizard/
    - assets/images/game_images/female/Enchantress/
    - assets/images/game_images/female/Knight/
    - assets/images/game_images/female/Musketeer/
    - assets/images/game_images/Enemy/FireDemon/
    - assets/images/game_images/Enemy/FireDemon/IDLE.png
    - .env

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
